# Generated by Django 3.2.25 on 2024-07-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_date', models.DateField()),
                ('Starts', models.TimeField()),
                ('Ends', models.TimeField()),
                ('What_Students_Should_Read_About', models.TextField()),
                ('What_Will_Be_taught', models.TextField()),
                ('Students_Cohourt', models.IntegerField()),
            ],
        ),
    ]
