# Generated by Django 3.2.25 on 2024-07-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassOn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='Tutor',
            field=models.CharField(default='Mr Iyanu', max_length=150),
        ),
    ]
