# Generated by Django 3.2.25 on 2024-07-12 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClassGr', '0002_schedule_tutor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='Tutor',
            new_name='instructor',
        ),
    ]
